services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=itkan
      - POSTGRES_PASSWORD=itkan
      - POSTGRES_DB=itkan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    command: ["celery", "-A", "app.services", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

    depends_on:
      - db
      - redis

volumes:
  postgres_data:
