services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=itkan
      - POSTGRES_PASSWORD=itkan
      - POSTGRES_DB=itkan_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
