"""initial async migration

Revision ID: 01121cbe7ecc
Revises: 0a5a3d784b0a
Create Date: 2025-10-27 21:35:46.566308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01121cbe7ecc'
down_revision = '0a5a3d784b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
