"""20_create_curriculums

Revision ID: 08448cae2d57
Revises: 690108e0a1f8
Create Date: 2026-01-20 12:31:00.256416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08448cae2d57'
down_revision = '690108e0a1f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LESSON', 'EXAM', 'VIDEO', name='unititemtype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('unit_item_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('exam_attempt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['daily_evaluations.id'], ),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_item_id'], ['unit_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('classes', sa.Column('curriculum_id', sa.Integer(), nullable=False))
    op.add_column('classes', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classes', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'classes', 'curriculums', ['curriculum_id'], ['id'])
    op.add_column('daily_evaluations', sa.Column('unit_item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'daily_evaluations', 'unit_items', ['unit_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_evaluations', type_='foreignkey')
    op.drop_column('daily_evaluations', 'unit_item_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'subject_id')
    op.drop_column('classes', 'curriculum_id')
    op.drop_table('student_progress')
    op.drop_table('unit_items')
    op.drop_table('units')
    op.drop_table('subjects')
    op.drop_table('curriculums')
    # ### end Alembic commands ###
