"""15_adjust_class_model

Revision ID: 2cc4fdb8fbd0
Revises: dc15629b5035
Create Date: 2025-11-19 18:29:24.246694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cc4fdb8fbd0'
down_revision = 'dc15629b5035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('evaluation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('classes', 'schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('classes', 'evaluation_config')
    # ### end Alembic commands ###
