"""19_create_reports

Revision ID: 690108e0a1f8
Revises: 87aca2ece780
Create Date: 2025-12-13 13:12:07.363411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '690108e0a1f8'
down_revision = '87aca2ece780'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_jobs_id'), table_name='reports_jobs')
    op.drop_table('reports_jobs')
    op.add_column('daily_evaluations', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_foreign_key('daily_evaluations_branch_id_fkey', 'daily_evaluations', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_constraint('daily_evaluations_branch_id_fkey', 'daily_evaluations', type_='foreignkey')
    op.drop_column('daily_evaluations', 'branch_id')
    op.create_table('reports_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('reports_jobs_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_jobs_pkey'))
    )
    op.create_index(op.f('ix_reports_jobs_id'), 'reports_jobs', ['id'], unique=False)
    # ### end Alembic commands ###
