"""21_staff_attendance

Revision ID: 36cee098f030
Revises: 08448cae2d57
Create Date: 2026-01-23 08:35:59.820219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36cee098f030'
down_revision = '08448cae2d57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_attendance_sources_id'), 'attendance_sources', ['id'], unique=False)
    op.create_table('school_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_calendars_branch_id'), 'school_calendars', ['branch_id'], unique=False)
    op.create_index(op.f('ix_school_calendars_id'), 'school_calendars', ['id'], unique=False)
    op.create_table('attendance_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'branch_id', 'date', name='uq_user_branch_date')
    )
    op.create_index(op.f('ix_attendance_daily_branch_id'), 'attendance_daily', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_date'), 'attendance_daily', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_daily_id'), 'attendance_daily', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_daily_user_id'), 'attendance_daily', ['user_id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['attendance_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_branch_id'), 'attendance_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_id'), 'attendance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_timestamp'), 'attendance_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_attendance_logs_user_id'), 'attendance_logs', ['user_id'], unique=False)
    op.create_table('calendar_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['school_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'date', name='uq_calendar_holiday_date')
    )
    op.create_index(op.f('ix_calendar_holidays_calendar_id'), 'calendar_holidays', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_holidays_id'), 'calendar_holidays', ['id'], unique=False)
    op.create_table('calendar_working_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=10), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['school_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id', 'weekday', name='uq_calendar_weekday')
    )
    op.create_index(op.f('ix_calendar_working_days_calendar_id'), 'calendar_working_days', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_working_days_id'), 'calendar_working_days', ['id'], unique=False)
    op.create_table('staff_work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['school_calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'calendar_id', name='uq_user_calendar')
    )
    op.create_index(op.f('ix_staff_work_schedules_calendar_id'), 'staff_work_schedules', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_staff_work_schedules_id'), 'staff_work_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_staff_work_schedules_user_id'), 'staff_work_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_work_schedules_user_id'), table_name='staff_work_schedules')
    op.drop_index(op.f('ix_staff_work_schedules_id'), table_name='staff_work_schedules')
    op.drop_index(op.f('ix_staff_work_schedules_calendar_id'), table_name='staff_work_schedules')
    op.drop_table('staff_work_schedules')
    op.drop_index(op.f('ix_calendar_working_days_id'), table_name='calendar_working_days')
    op.drop_index(op.f('ix_calendar_working_days_calendar_id'), table_name='calendar_working_days')
    op.drop_table('calendar_working_days')
    op.drop_index(op.f('ix_calendar_holidays_id'), table_name='calendar_holidays')
    op.drop_index(op.f('ix_calendar_holidays_calendar_id'), table_name='calendar_holidays')
    op.drop_table('calendar_holidays')
    op.drop_index(op.f('ix_attendance_logs_user_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_timestamp'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_branch_id'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_attendance_daily_user_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_id'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_date'), table_name='attendance_daily')
    op.drop_index(op.f('ix_attendance_daily_branch_id'), table_name='attendance_daily')
    op.drop_table('attendance_daily')
    op.drop_index(op.f('ix_school_calendars_id'), table_name='school_calendars')
    op.drop_index(op.f('ix_school_calendars_branch_id'), table_name='school_calendars')
    op.drop_table('school_calendars')
    op.drop_index(op.f('ix_attendance_sources_id'), table_name='attendance_sources')
    op.drop_table('attendance_sources')
    # ### end Alembic commands ###
