"""22_staff_evaluations

Revision ID: 41ab7556e9d7
Revises: 36cee098f030
Create Date: 2026-01-30 21:07:11.156021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ab7556e9d7'
down_revision = '36cee098f030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_cycles_id'), 'evaluation_cycles', ['id'], unique=False)
    op.create_table('kpi_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_templates_created_by_user_id'), 'kpi_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_kpi_templates_id'), 'kpi_templates', ['id'], unique=False)
    op.create_table('employee_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_user_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['evaluation_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['kpi_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_user_id', 'cycle_id', name='uq_employee_evaluation_per_cycle')
    )
    op.create_index(op.f('ix_employee_evaluations_cycle_id'), 'employee_evaluations', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_employee_evaluations_employee_user_id'), 'employee_evaluations', ['employee_user_id'], unique=False)
    op.create_index(op.f('ix_employee_evaluations_evaluator_user_id'), 'employee_evaluations', ['evaluator_user_id'], unique=False)
    op.create_index(op.f('ix_employee_evaluations_id'), 'employee_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_employee_evaluations_template_id'), 'employee_evaluations', ['template_id'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['kpi_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_id'), 'kpis', ['id'], unique=False)
    op.create_index(op.f('ix_kpis_template_id'), 'kpis', ['template_id'], unique=False)
    op.create_table('evaluation_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['employee_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_comments_evaluation_id'), 'evaluation_comments', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_comments_id'), 'evaluation_comments', ['id'], unique=False)
    op.create_table('evaluation_kpi_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['employee_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'kpi_id', name='uq_evaluation_kpi_score')
    )
    op.create_index(op.f('ix_evaluation_kpi_scores_evaluation_id'), 'evaluation_kpi_scores', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_kpi_scores_id'), 'evaluation_kpi_scores', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_kpi_scores_kpi_id'), 'evaluation_kpi_scores', ['kpi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_kpi_scores_kpi_id'), table_name='evaluation_kpi_scores')
    op.drop_index(op.f('ix_evaluation_kpi_scores_id'), table_name='evaluation_kpi_scores')
    op.drop_index(op.f('ix_evaluation_kpi_scores_evaluation_id'), table_name='evaluation_kpi_scores')
    op.drop_table('evaluation_kpi_scores')
    op.drop_index(op.f('ix_evaluation_comments_id'), table_name='evaluation_comments')
    op.drop_index(op.f('ix_evaluation_comments_evaluation_id'), table_name='evaluation_comments')
    op.drop_table('evaluation_comments')
    op.drop_index(op.f('ix_kpis_template_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_id'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_employee_evaluations_template_id'), table_name='employee_evaluations')
    op.drop_index(op.f('ix_employee_evaluations_id'), table_name='employee_evaluations')
    op.drop_index(op.f('ix_employee_evaluations_evaluator_user_id'), table_name='employee_evaluations')
    op.drop_index(op.f('ix_employee_evaluations_employee_user_id'), table_name='employee_evaluations')
    op.drop_index(op.f('ix_employee_evaluations_cycle_id'), table_name='employee_evaluations')
    op.drop_table('employee_evaluations')
    op.drop_index(op.f('ix_kpi_templates_id'), table_name='kpi_templates')
    op.drop_index(op.f('ix_kpi_templates_created_by_user_id'), table_name='kpi_templates')
    op.drop_table('kpi_templates')
    op.drop_index(op.f('ix_evaluation_cycles_id'), table_name='evaluation_cycles')
    op.drop_table('evaluation_cycles')
    # ### end Alembic commands ###
