"""9_edit_roles_permissions

Revision ID: 605a2dd5b2be
Revises: 348ec5471b93
Create Date: 2025-11-12 17:53:10.744976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605a2dd5b2be'
down_revision = '348ec5471b93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('permissions', sa.Column('name_ar', sa.Text(), nullable=False))
    op.add_column('permissions', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('name_ar', sa.String(length=50), nullable=False))
    op.add_column('roles', sa.Column('description_ar', sa.Text(), nullable=False))
    op.drop_constraint(op.f('roles_name_in_arabic_key'), 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name_ar'])
    op.drop_column('roles', 'name_in_arabic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name_in_arabic', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(op.f('roles_name_in_arabic_key'), 'roles', ['name_in_arabic'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'description_ar')
    op.drop_column('roles', 'name_ar')
    op.drop_column('permissions', 'description_ar')
    op.drop_column('permissions', 'name_ar')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###
