"""15_refactor_attendance_and_evaluations

Revision ID: 76c2451380d6
Revises: dc15629b5035
Create Date: 2025-11-21 13:05:42.783528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76c2451380d6'
down_revision = 'dc15629b5035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.add_column('classes', sa.Column('evaluation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('classes', 'schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('daily_evaluations', sa.Column('recorded_by_user_id', sa.Integer(), nullable=False))
    attendance_status_enum = sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus')
    attendance_status_enum.create(op.get_bind())
    op.add_column('daily_evaluations', 
        sa.Column('attendance_status', attendance_status_enum, nullable=False, server_default='PRESENT')
    )
    op.add_column('daily_evaluations', sa.Column('evaluation_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('daily_evaluations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('uq_evaluation_student_date'), 'daily_evaluations', type_='unique')
    op.create_unique_constraint('uq_evaluation_student_class_date', 'daily_evaluations', ['student_id', 'date', 'class_id'])
    op.drop_constraint(op.f('daily_evaluations_recorded_by_fkey'), 'daily_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'daily_evaluations', 'users', ['recorded_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('daily_evaluations', 'memorization_percent')
    op.drop_column('daily_evaluations', 'behavior_score')
    op.drop_column('daily_evaluations', 'recorded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_evaluations', sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_evaluations', sa.Column('behavior_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_evaluations', sa.Column('memorization_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'daily_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('daily_evaluations_recorded_by_fkey'), 'daily_evaluations', 'users', ['recorded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_evaluation_student_class_date', 'daily_evaluations', type_='unique')
    op.create_unique_constraint(op.f('uq_evaluation_student_date'), 'daily_evaluations', ['student_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_evaluations', 'updated_at')
    op.drop_column('daily_evaluations', 'evaluation_grades')
    op.drop_column('daily_evaluations', 'attendance_status')
    op.drop_column('daily_evaluations', 'recorded_by_user_id')
    op.alter_column('classes', 'schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('classes', 'evaluation_config')
    op.create_table('attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('recorded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('attendance_class_id_fkey')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('attendance_recorded_by_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('attendance_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('student_id', 'date', name=op.f('uq_attendance_student_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    # ### end Alembic commands ###
