"""11_drop exam tables

Revision ID: 7cdb6f784cb0
Revises: 605a2dd5b2be
Create Date: 2025-11-13 16:54:08.948688

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7cdb6f784cb0"
down_revision = "605a2dd5b2be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exam_answers_id"), table_name="exam_answers")
    op.drop_table("exam_answers")
    op.drop_index(op.f("ix_exam_questions_exam_id"), table_name="exam_questions")
    op.drop_index(op.f("ix_exam_questions_question_id"), table_name="exam_questions")
    op.drop_table("exam_questions")
    op.drop_index(op.f("ix_exam_attempts_id"), table_name="exam_attempts")
    op.drop_table("exam_attempts")
    op.drop_index(op.f("ix_exams_id"), table_name="exams")
    op.drop_table("exams")
    op.add_column(
        "question_bank", sa.Column("title", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "question_bank", sa.Column("difficulty", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "question_bank",
        sa.Column("correct_answer", sa.String(length=20), nullable=True),
    )
    op.add_column("question_bank", sa.Column("is_shared", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_question_bank_id"), table_name="question_bank")
    op.create_unique_constraint(
        "uq_title_created_by", "question_bank", ["title", "created_by"]
    )
    op.drop_column("question_bank", "text")
    op.drop_column("question_bank", "subject")
    op.drop_column("question_bank", "correct_options")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question_bank",
        sa.Column(
            "correct_options",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "question_bank",
        sa.Column(
            "subject", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "question_bank",
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("uq_title_created_by", "question_bank", type_="unique")
    op.create_index(op.f("ix_question_bank_id"), "question_bank", ["id"], unique=False)
    op.drop_column("question_bank", "is_shared")
    op.drop_column("question_bank", "correct_answer")
    op.drop_column("question_bank", "difficulty")
    op.drop_column("question_bank", "title")
    op.create_table(
        "exams",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('exams_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column("branch_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("class_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "start_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "end_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("duration_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_published", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name="exams_branch_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name="exams_class_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="exams_created_by_fkey",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="exams_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_exams_id"), "exams", ["id"], unique=False)
    op.create_table(
        "exam_attempts",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('exam_attempts_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("exam_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "score",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name="exam_attempts_exam_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name="exam_attempts_student_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="exam_attempts_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_exam_attempts_id"), "exam_attempts", ["id"], unique=False)
    op.create_table(
        "exam_questions",
        sa.Column("exam_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
            name=op.f("exam_questions_exam_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
            name=op.f("exam_questions_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "exam_id", "question_id", name=op.f("exam_questions_pkey")
        ),
    )
    op.create_index(
        op.f("ix_exam_questions_question_id"),
        "exam_questions",
        ["question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exam_questions_exam_id"), "exam_questions", ["exam_id"], unique=False
    )
    op.create_table(
        "exam_answers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("attempt_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chosen_option", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exam_attempts.id"],
            name=op.f("exam_answers_attempt_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question_bank.id"],
            name=op.f("exam_answers_question_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("exam_answers_pkey")),
    )
    op.create_index(op.f("ix_exam_answers_id"), "exam_answers", ["id"], unique=False)
    # ### end Alembic commands ###
