"""13_make_role_description_nullable

Revision ID: 9cce40b7647e
Revises: 55cf1b7f3f9e
Create Date: 2025-11-13 18:24:19.560315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cce40b7647e'
down_revision = '55cf1b7f3f9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('roles', 'description_ar',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_staff_user_id', 'staff', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_staff_user_id', 'staff', type_='unique')
    op.alter_column('roles', 'description_ar',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
