"""edit notification model

Revision ID: a252f6e29415
Revises: af4f929dc0b4
Create Date: 2025-11-05 13:07:49.446042

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a252f6e29415"
down_revision = "4689a6fb9cbe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("failed_message", sa.String(length=255), nullable=True),
    )
    op.alter_column(
        "notifications",
        "channel",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "template",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "notifications",
        "payload",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "notifications",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column("roles", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roles", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "notifications",
        "status",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "payload",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "notifications", "template", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "notifications",
        "channel",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("notifications", "failed_message")
    # ### end Alembic commands ###
