"""24_create_enrolments

Revision ID: c861674cd197
Revises: 7fe3882bb31d
Create Date: 2026-07-19 15:51:30.001212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c861674cd197'
down_revision = '7fe3882bb31d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolment_pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('months_paid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['enrolment_pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrolments')
    op.drop_table('enrolment_pricing_plans')
    # ### end Alembic commands ###
