"""5_add unique constraint to branch name and email, and put status enum

Revision ID: d0c6dc826335
Revises: 4457cb957767
Create Date: 2025-11-06 20:41:08.910369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c6dc826335'
down_revision = '4457cb957767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('status', sa.String(length=10), nullable=False))
    op.alter_column('branches', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint('uq_branches_email', 'branches', ['email'])
    op.create_unique_constraint('uq_branches_name', 'branches', ['name'])
    op.drop_column('branches', 'active')
    op.add_column('classes', sa.Column('status', sa.String(length=10), nullable=False))
    op.create_check_constraint(
        'ck_branches_status',
        'branches',
        "status IN ('active', 'deactive')"
    )
    op.create_check_constraint(
        'ck_users_status',
        'users',
        "status IN ('active', 'deactive', 'pending', 'rejected')"
    )
    op.create_check_constraint(
        'ck_classes_status',
        'branches',
        "status IN ('active', 'deactive')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'status')
    op.add_column('branches', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_branches_name', 'branches', type_='unique')
    op.drop_constraint('uq_branches_email', 'branches', type_='unique')
    op.alter_column('branches', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('branches', 'status')
    op.drop_constraint('ck_branches_status', 'branches', type_='check')
    op.drop_constraint('ck_users_status', 'users', type_='check')
    op.drop_constraint('ck_classes_status', 'classes', type_='check')

    # ### end Alembic commands ###
