"""add roles, permissions, user-role relations

Revision ID: d185e9589a34
Revises: f2567b26aa80
Create Date: 2025-10-29 20:45:19.344913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd185e9589a34'
down_revision = 'f2567b26aa80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
