"""14_make_role_description_nullable

Revision ID: dc15629b5035
Revises: 523308d88916
Create Date: 2025-11-14 19:31:24.437106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc15629b5035'
down_revision = '523308d88916'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('roles', 'description_ar',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_staff_user_id', 'staff', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_staff_user_id', 'staff', type_='unique')
    op.alter_column('roles', 'description_ar',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
