"""6_remove branch_id from staff and student

Revision ID: f94ca4c38486
Revises: d0c6dc826335
Create Date: 2025-11-07 10:10:25.089617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94ca4c38486'
down_revision = 'd0c6dc826335'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('staff_branch_id_fkey'), 'staff', type_='foreignkey')
    op.drop_column('staff', 'branch_id')
    op.drop_constraint(op.f('students_branch_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_branch_id_fkey'), 'students', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('staff', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('staff_branch_id_fkey'), 'staff', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
